version: "2"
exclude_patterns:
  - ".*/"
  - "build/"
  - "host-app/"
  - "images/"
  - "inbox-ui-tests-app/"
  - "sample-apps/"
  - "scripts/"
  - "swift-sdk/Resources/"
  - "swift-sdk/Internal/Dwifft"
  - "tests/"
  - "ui-tests-app/"
  - ".*"
  - "*.h"
  - "*.md"
  - "*.plist"
  - "codecov.yml"
  - "*.podspec"
  - "LICENSE"
  - "Package.swift"
  - "swift-sdk.xcodeproj"
