name: Build and test

on: pull_request

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and test
      run: |
        xcodebuild test -project swift-sdk.xcodeproj -scheme swift-sdk -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' -enableCodeCoverage YES CODE_SIGNING_REQUIRED=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty || exit 1
        
    - name: CocoaPods lint
      run: pod lib lint --allow-warnings

    - name: Upload coverage report to codecov.io
      run: bash <(curl -s https://codecov.io/bash) -J 'host-app' -J 'ui-tests-app' -J 'inbox-ui-tests-app'